---
title: "TEST: PAN_1960_IPUMS"
author: "CORESIDENCE PROJECT"
date: "Reference: HE-ERC-2021-AdG-GA No 101052787-CORESIDENCE"
abstract: "**Abstract: **This document provides a summary description of variables included in the samples downloaded from IPUMS to build the CORESIDENCE database. If you need to report any mistake, please contact _jgaleano@ced.uab.es_. You can access the source R-code to render this document at: [GitHub: CORESIDENCE](https://github.com/JuanGaleano/CORESIDENCE/blob/main/TEST_IPUMS.qmd)"
mainfont: Arial
monofont: Arial
format: pdf
editor: visual
---

```{r}
#| echo: false
#| warning: false
library(purrr)
library(knitr)
library(kableExtra)
library(tidyverse)
library(RColorBrewer)

load("G:\\Shared drives\\CORESIDENCE\\WP2_DATA\\2_1_Input Data\\CENSUS_IPUMS\\PAN_1960_IPUMS.Rdata")

load("G:\\Shared drives\\CORESIDENCE\\WP2_DATA\\2_1_Input Data\\CENSUS_IPUMS\\A1_IMPUS_MOTHERS\\all_NAs_list.Rdata")

VARIABLE_TO_CHANGE<-all_NAs_list[[as.character(unique(df$SAMPLE))]]
df$AGE2B<-with(df, ifelse(AGE<=4, "0-4",
                   ifelse(AGE<=9, "5-9", 
                   ifelse(AGE<=14, "10-14",
                   ifelse(AGE<=19, "15-19",
                   ifelse(AGE<=24, "20-24",
                   ifelse(AGE<=29, "25-29",
                   ifelse(AGE<=34, "30-34",
                   ifelse(AGE<=39, "35-39",
                   ifelse(AGE<=44, "40-44",
                   ifelse(AGE<=49, "45-49",
                   ifelse(AGE<=54, "50-54",
                   ifelse(AGE<=59, "55-59",
                   ifelse(AGE<=64, "60-64",
                   ifelse(AGE<=69, "65-69",
                   ifelse(AGE<=74, "70-74",
                   ifelse(AGE<=79, "75-79",
                   ifelse(AGE<=84, "80-84",
                   ifelse(AGE<=89, "85-89",
                   ifelse(AGE<=94, "90-94",
                   ifelse(AGE<=99, "95-99",
                   ifelse(AGE<=104, "100-104",
                   ifelse(AGE<=109, "105-109",
                   ifelse(AGE<=114, "110-114","mal"
                          ))))))))))))))))))))))))

df$AGE2B<-as.factor(df$AGE2B)
df$AGE2B<-factor(df$AGE2B, levels=c("0-4", "5-9", "10-14",
                                    "15-19","20-24","25-29",
                                    "30-34","35-39","40-44",
                                    "45-49","50-54","55-59",
                                    "60-64","65-69","70-74",
                                    "75-79", "80-84","85-89",
                                    "90-94","95-99","100-104",
                                    "105-109","110-114"))


```

------------------------------------------------------------------------

## COUNTRY: `r toupper(as.character(as_factor(unique(df$COUNTRY))))` \| YEAR: `r as.character(as_factor(unique(df$YEAR)))` \| SAMPLE SIZE: `r formatC(nrow(df), format="f", big.mark=",",digits=0)` CASES

### 1. VARIABLES with ALL NAs

**Number of variables with all NAs:** `r unique(length(df %>% keep(~all(is.na(.x))) %>% names))`.

```{r fig.width=12, fig.height=8}
#| echo: false
#| warning: FALSE
a<-as.data.frame(df %>% keep(~all(is.na(.x))) %>% names)
colnames(a)<-"Name"
base<-df
split_a<-split(a, f=a$Name)
all_NAs_list <- lapply(split_a, function(df) {
  df<-attributes(base[,df[[1]]])$var_desc
  df
})
df_all_NAs<-as.data.frame(do.call('rbind',all_NAs_list ))
df_all_NAs_f<-data.frame(Name=row.names(df_all_NAs),
                         Description=df_all_NAs$V1)

kbl(df_all_NAs_f,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "7em")%>%
column_spec(2, width = "35em")

```

### 1.1 VARIABLES with NAs

```{r fig.width=12, fig.height=4.5}
#| echo: false
#| warning: FALSE
if((ifelse(length(setdiff(colnames(df[colSums(is.na(df))>0]),
         df %>% keep(~all(is.na(.x))) %>% names))==0,0,1))==0){
print("All variables with NAs included in this sample have 100% NAs.")
} else {
df_nas<-df%>%
  select(colnames(df[colSums(is.na(df))>0]))%>%
  select(-(df %>% keep(~all(is.na(.x))) %>% names)) %>%  
  summarise_all(funs(sum(is.na(.))/length(df$COUNTRY)))%>%
  pivot_longer(cols = everything())%>%
  arrange(-value)%>%
  mutate(name=fct_reorder(name, value, .desc = FALSE))
 
df_nas$cat<-with(df_nas, as.factor(ifelse(value<0.01,"<1%",
                 ifelse(value<0.03,"1-3%",
                 ifelse(value<0.05,"3-5%",
                 ifelse(value<0.1,"5-10%",
                 ifelse(value<0.25,"10-25%",
                 ifelse(value<0.5,"25-50%",">50%"
                        )))))))) 

df_nas$cat<-factor(df_nas$cat, levels=c("<1%",
                                        "1-3%",
                                        "3-5%",
                                        "5-10%",
                                        "10-25%",
                                        "25-50%",">50%"))

myColors <- c(brewer.pal(7, "Reds"))
  
names(myColors) <- levels(df_nas$cat)

ggplot(df_nas,aes(x=name, y=value, fill=factor(cat)))+
  coord_flip()+
  expand_limits(y = 1)+
  scale_y_continuous(breaks = seq(0,1, by= .2),
                     labels = scales::percent)+
  scale_fill_manual(values=myColors)+
  geom_bar(stat="identity", 
           size=.25,
           color="black")+
  geom_text(aes(label = round(value*100,2)),size=4.5,hjust = -.25)+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black",face="bold", size = 15),
        legend.position=c("none"),
        axis.text.x = element_text(angle = 0,vjust=0.5, size=15,colour="black"),
        axis.ticks.x = element_blank(),
        axis.text  = element_text(angle = 0,vjust=0.5, size=15,colour="black"),
        axis.title  = element_blank(),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour="#f2f2f2")) 
}
```

### 2. Group Quarter and unrelated, GQ and UNREL

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
GQ_UNREL<-df%>%
  select(GQ, UNREL)
```

### 2.1 Frequencies GQ

`r attributes(df$GQ)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
GQ<- GQ_UNREL%>%
  group_by(as_factor(GQ)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(GQ, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 2.2 Frequencies UNREL

`r attributes(df$UNREL)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
UNREL<- GQ_UNREL%>%
  group_by(as_factor(UNREL)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(UNREL, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 3. Crosstables

### 3.1 MOMLOC x RELATE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE

RELATE_MOMLOC<-df %>% 
  select(MOMLOC,RELATE)

kbl(table(as_factor(RELATE_MOMLOC$MOMLOC),as_factor(RELATE_MOMLOC$RELATE),useNA="always"),
    booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center",font_size = 9)%>%column_spec(1, width = "6em")%>%
  column_spec(2, width = "4em")%>%
  column_spec(3, width = "4em")%>%
  column_spec(4, width = "4em")%>%
  column_spec(5, width = "4em")%>%
  column_spec(6, width = "4em")%>%
  column_spec(7, width = "4em")%>%
  column_spec(8, width = "4em")
```

### 3.2 POPLOC x RELATE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
RELATE_POPLOC<-df %>% 
  select(POPLOC,RELATE)

kbl(table(as_factor(RELATE_POPLOC$POPLOC),as_factor(RELATE_POPLOC$RELATE),useNA="always"),
    booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center",font_size = 9)%>%column_spec(1, width = "6em")%>%
  column_spec(2, width = "4em")%>%
  column_spec(3, width = "4em")%>%
  column_spec(4, width = "4em")%>%
  column_spec(5, width = "4em")%>%
  column_spec(6, width = "4em")%>%
  column_spec(7, width = "4em")%>%
  column_spec(8, width = "4em")
```

### 3.3 SPLOC x RELATE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
RELATE_SPLOC<-df %>% 
  select(SPLOC,RELATE)

kbl(table(as_factor(RELATE_SPLOC$SPLOC),as_factor(RELATE_SPLOC$RELATE),useNA="always"),
    booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center",font_size = 9)%>%column_spec(1, width = "6em")%>%
  column_spec(2, width = "4em")%>%
  column_spec(3, width = "4em")%>%
  column_spec(4, width = "4em")%>%
  column_spec(5, width = "4em")%>%
  column_spec(6, width = "4em")%>%
  column_spec(7, width = "4em")%>%
  column_spec(8, width = "4em")
```

### 3.4 AGE x SEX x MARST (Graph)

```{r fig.width=12, fig.height=10}
#| echo: false
#| warning: FALSE

variable<-"MARST"
variables_NAs<-df %>% keep(~all(is.na(.x))) %>% names

if(ifelse((variable %in% variables_NAs),1,0)==1){
print("Variable MARST has 100% NAs.")
} else {
SEX<- df%>% 
  group_by(as_factor(SEX),as_factor(df$AGE2B),as_factor(df$MARST)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

colnames(SEX)<-c("Sex", "Age2", "Mars", "n", "rel")

levels(SEX$Mars)<-c("NIU (not in universe)",
                    "Single /\nnever married",
                     "Married /\nin union",
                     "Separated/divorced /\nspouse absent",
                     "Widowed","Unknown /\nmissing")

ggplot(SEX[SEX$Sex!="Unknown",], aes(x=Age2, y=n,fill=Mars)) + 
  geom_bar(stat = "identity", colour="black", size=.01)+
  coord_flip()+
  facet_wrap(Sex~Mars, ncol=length(unique(SEX$Mars)))+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size = 12),
        legend.position="none",
        axis.text.y = element_text(colour="black", size = 14),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face="bold"),
        strip.text.y = element_text(size = 14, face="bold"),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour=NA))
}
```

### 3.5 AGE x SEX x EDATTAIN (Graph)

```{r fig.width=12, fig.height=10}
#| echo: false
#| warning: FALSE

variable<-"EDATTAIN"
variables_NAs<-df %>% keep(~all(is.na(.x))) %>% names

if(ifelse((variable %in% variables_NAs),1,0)==1){
print("Variable EDATTAIN has 100% NAs.")
} else {
EDATTAIN<- df%>% 
  group_by(as_factor(SEX),as_factor(df$AGE2B),as_factor(df$EDATTAIN)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

colnames(EDATTAIN)<-c("Sex", "Age2", "Education", "n", "rel")

levels(EDATTAIN$Education)<-c("NIU\n(not in universe)",
                              "Less than\nprimary completed",
                              "Primary\ncompleted",
                              "Secondary\ncompleted",
                              "University\ncompleted",
                              "Unknown")

ggplot(EDATTAIN[EDATTAIN$Sex!="Unknown",], aes(x=Age2, y=n,fill=Education)) + 
  geom_bar(stat = "identity", colour="black", size=.01)+
  coord_flip()+
  facet_wrap (Sex~Education, ncol=length(unique(EDATTAIN$Education)))+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size = 12),
        legend.position="none",
        axis.text.y = element_text(colour="black", size = 14),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face="bold"),
        strip.text.y = element_text(size = 14, face="bold"),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour=NA))
}
```

### 3.6 AGE x SEX x RELATE (Graph)

```{r fig.width=12, fig.height=10}
#| echo: false
#| warning: FALSE

variable<-"RELATE"
variables_NAs<-df %>% keep(~all(is.na(.x))) %>% names

if(ifelse((variable %in% variables_NAs),1,0)==1){
print("Variable RELATE has 100% NAs.")
} else {

RELATE<- df%>% 
  group_by(as_factor(SEX),as_factor(df$AGE2B),as_factor(df$RELATE)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

colnames(RELATE)<-c("Sex", "Age2", "Relate", "n", "rel")

levels(RELATE$Relate)<-c("Head",
                         "Spouse/\npartner",
                         "Child", 
                         "Other\nrelative",
                         "Other relative or\n non-relative",
                         "Non\nrelative",
                         "Unknown")

ggplot(RELATE[RELATE$Sex!="Unknown",], aes(x=Age2, y=n,fill=Relate)) + 
  geom_bar(stat = "identity", colour="black", size=.01)+
  coord_flip()+
  facet_wrap (Sex~Relate, ncol=length(unique(RELATE$Relate)))+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size = 12),
        legend.position="none",
        axis.text.y = element_text(colour="black", size = 14),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face="bold"),
        strip.text.y = element_text(size = 14, face="bold"),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour=NA))
}
```

### 4. POPULATION PYRAMID (AGE x SEX)

```{r fig.width=12, fig.height=8.5}
#| echo: false
#| warning: FALSE
SEX_AGE<-df%>%
  select(SEX,AGE)%>%
  filter(SEX!=9)

SEX_AGE$id<-paste(SEX_AGE$AGE,SEX_AGE$SEX, sep="-")
SEX_AGE <- SEX_AGE %>% 
  group_by(id,SEX,AGE) %>%
  summarise(pop = n())

dfedades<-data.frame(AGE=rep(c(0:110),2),
                     SEX=rep(c(1,2),each=111))

dfedades$id<-paste(dfedades$AGE,dfedades$SEX, sep="-")

SEX_AGE<-as.data.frame(SEX_AGE)
dfedades<-as.data.frame(dfedades)
df_PIR <- data.frame(dfedades,
                     SEX_AGE[match(dfedades[,"id"],
                                   SEX_AGE[,"id"]),])

df_PIR<-df_PIR %>%
        select(AGE,SEX,id,pop)%>%
        mutate(pop2=ifelse(SEX==1, pop*-1, pop))

df_PIR$pop2[is.na(df_PIR$pop2)] <- 0

gg_color_hue <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=65, c=100)[1:n]
}
cols = gg_color_hue(2)
df_PIR$SEX<-as.factor(df_PIR$SEX)
levels(df_PIR$SEX)<-c("Male", "Female")

ggplot(df_PIR, aes(x=AGE, y=pop2, fill=factor(SEX)))+
  geom_bar(colour = I("Black"),
           stat="identity", 
           position="identity", 
           size=.1, alpha =1)+
  coord_flip()+
  labs(#title=unique(df$ndis),
       x="Age",
       y="")+
  scale_fill_manual(values = rev(c(cols)),
                    guide = guide_legend(direction = "horizontal",
                                         nrow = 1,
                                         keywidth=5,
                                         keyheight=1,
                                         label.position = "bottom"))+
  scale_x_continuous(breaks=seq(0,110,5))+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black",face="bold", size = 15),
        legend.position="bottom",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text  = element_text(angle = 0,vjust=0.5, size=15,colour="black"),
        axis.title  = element_text(angle = 0,vjust=0.5, size=15,colour="black"),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour="#f2f2f2")) 

```

### 4.1 Frequencies SEX

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
SEX<- df%>% 
  select(SEX)%>%
  group_by(as_factor(SEX)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(SEX,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 4.2 Frequencies AGE2

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
AGE2<- df%>% 
  select(AGE2B)%>%
  group_by(as_factor(AGE2B)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(AGE2,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 5. RELATION OF INDIVIDUAL TO THE HEAD OF THE HOUSEHOLD: RELATE

`r attributes(df$RELATE)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
REL<-df%>%
  select(RELATE, RELATED)
```

### 5.1 Frequencies RELATE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
RELATE<- REL%>% 
  group_by(as_factor(RELATE)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(RELATE,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 5.2 Frequencies RELATED

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
RELATED<- REL%>% 
  group_by(as_factor(RELATED)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(RELATED,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 5.3 Population pyramid (AGE x SEX x RELATE)

```{r fig.width=12, fig.height=8.5}
#| echo: false
#| warning: FALSE
SEX_AGE_RELATE<-df%>%
  select(SEX,AGE,RELATE)%>%
  filter(SEX!=9)
SEX_AGE_RELATE$id<-paste(SEX_AGE_RELATE$AGE,SEX_AGE_RELATE$SEX,SEX_AGE_RELATE$RELATE, sep="-")
SEX_AGE_RELATE <- SEX_AGE_RELATE %>% group_by(id,SEX,AGE,RELATE) %>%
  summarise(pop = n())
dfedades_relate<-data.frame(AGE=rep(c(0:110),14),
                     SEX=rep(rep(c(1,2),each=111),7),
                     RELATE=rep(rep(c(1:7), each=111),2))
dfedades_relate$id<-paste(dfedades_relate$AGE,dfedades_relate$SEX,dfedades_relate$RELATE, sep="-")
SEX_AGE_RELATE<-as.data.frame(SEX_AGE_RELATE)
dfedades_relate<-as.data.frame(dfedades_relate)
df_PIR_RELATE <- data.frame(dfedades_relate,
               SEX_AGE_RELATE[match(dfedades_relate[,"id"],
                                          SEX_AGE_RELATE[,"id"]),])
df_PIR_RELATE<-df_PIR_RELATE %>%
  select(AGE,SEX,RELATE,id,pop)%>%
  mutate(pop2=ifelse(SEX==1, pop*-1, pop))
df_PIR_RELATE$pop2[is.na(df_PIR_RELATE$pop2)] <- 0
cols_relate = gg_color_hue(7)
df_PIR_RELATE$SEX<-as.factor(df_PIR_RELATE$SEX)
levels(df_PIR_RELATE$SEX)<-c("Male", "Female")
df_PIR_RELATE$RELATE<-as.factor(df_PIR_RELATE$RELATE)
levels(df_PIR_RELATE$RELATE)<-c("Head","Spouse/partner","Child","Other relative","Non-relative","Other relative or\nnon-relative","Unknown")
ggplot(df_PIR_RELATE, aes(x=AGE, y=pop2, fill=factor(RELATE)))+
  geom_bar(colour = I("Black"),
           stat="identity", 
           position="stack", 
           size=.3, alpha =1)+
  coord_flip()+
  labs(#title=unique(df$ndis),
    x="Age",
    y="")+
  scale_fill_manual(values = c(cols_relate),
                    guide = guide_legend(direction = "horizontal",
                                         nrow = 1,
                                         keywidth=7,
                                         keyheight=1.25,
                                         label.position = "bottom"))+
  scale_x_continuous(breaks=seq(0,110,5))+
  theme(plot.title = element_text(lineheight=5.6, vjust=1.5,size=12, face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size = 12),
        legend.position="bottom",
        axis.text.x = element_blank(),
        axis.text.y = element_text(colour="black", size = 12),
        axis.title.y = element_text(colour="black", size = 12),
        axis.ticks.x = element_blank(),
        legend.background = element_rect(fill = NA),
        panel.background = element_rect(fill = "#ffffff"),
        plot.background = element_rect(fill = "#ffffff"),
        panel.grid.major=element_line(colour="#f2f2f2",size = .2), 
        panel.grid.minor=element_line(colour="#f2f2f2"))  


```

### 6. NATIVITY and COUNTRY OF BIRTH: NATIVITY, BPLCOUNTRY

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NATIVITY_BPLCOUNTRY<-df%>%
  select(NATIVITY,BPLCOUNTRY)
```

### 6.1 Frequencies NATIVITY

`r attributes(df$NATIVITY)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NATIVITY<- NATIVITY_BPLCOUNTRY%>% 
  group_by(as_factor(NATIVITY)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NATIVITY, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 6.2 Frequencies BPLCOUNTRY

`r attributes(df$BPLCOUNTRY)$var_desc`

**Number of unique codes:** `r length(unique(df$BPLCOUNTRY))`.\
**Unique values:** `r unique(as_factor(df$BPLCOUNTRY))`.

**Table: Ranking top 10**

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
BPLCOUNTRY<- NATIVITY_BPLCOUNTRY%>% 
  group_by(as_factor(BPLCOUNTRY)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2)) %>% 
  arrange(-n)%>% 
  head(10)

kbl(BPLCOUNTRY, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 7. HEADLOC, MOMLOC, POPLOC, SPLOC

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
LOC<-df%>%
  select(HEADLOC,MOMLOC,POPLOC,SPLOC)
```

### 7.1 Frequencies HEADLOC

`r attributes(df$HEADLOC)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
HEADLOC<- LOC%>% #nota: tambien hay informacion sobre la cantidad de habitaciones lo que puede dar una idea del tamaño de la casa
  mutate(fct_explicit_na(as_factor(HEADLOC), na_level = "(Missing)"))%>%
  group_by(as_factor(HEADLOC)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(HEADLOC,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 7.2 Frequencies MOMLOC

`r attributes(df$MOMLOC)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
MOMLOC<- LOC%>% #nota: tambien hay informacion sobre la cantidad de habitaciones lo que puede dar una idea del tamaño de la casa
  mutate(fct_explicit_na(as_factor(MOMLOC), na_level = "(Missing)"))%>%
  group_by(as_factor(MOMLOC)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(MOMLOC,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 7.3 Frequencies POPLOC

`r attributes(df$POPLOC)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
POPLOC<- LOC%>% #nota: tambien hay informacion sobre la cantidad de habitaciones lo que puede dar una idea del tamaño de la casa
  mutate(fct_explicit_na(as_factor(POPLOC), na_level = "(Missing)"))%>%
  group_by(as_factor(POPLOC)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(POPLOC,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 7.4 Frequencies SPLOC

`r attributes(df$SPLOC)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
SPLOC<- LOC%>% #nota: tambien hay informacion sobre la cantidad de habitaciones lo que puede dar una idea del tamaño de la casa
  mutate(fct_explicit_na(as_factor(SPLOC), na_level = "(Missing)"))%>%
  group_by(as_factor(SPLOC)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(SPLOC,booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8. NFAMS, NCOUPLES, NMOTHERS, NFATHERS, NCHILD, NCHLT5

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
N_FAM<-df%>%
  select(NFAMS, NCOUPLES, NMOTHERS, NFATHERS,NCHILD,NCHLT5)
```

### 8.1 Frequencies NFAMS

`r attributes(df$NFAMS)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NFAMS<- N_FAM%>% 
  group_by(as_factor(NFAMS)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NFAMS, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8.2 Frequencies NCOUPLES

`r attributes(df$NCOUPLES)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NCOUPLES<- N_FAM%>% 
  group_by(as_factor(NCOUPLES)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NCOUPLES, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8.3 Frequencies NMOTHERS

`r attributes(df$NMOTHERS)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NMOTHERS<- N_FAM%>% 
  group_by(as_factor(NMOTHERS)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NMOTHERS, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8.4 Frequencies NFATHERS

`r attributes(df$NFATHERS)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NFATHERS<- N_FAM%>% 
  group_by(as_factor(NFATHERS)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NFATHERS, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8.5 Frequencies NCHILD

`r attributes(df$NCHILD)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NCHILD<- N_FAM%>% 
  group_by(as_factor(NCHILD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NCHILD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 8.6 Frequencies NCHLT5

`r attributes(df$NCHLT5)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
NCHLT5<- N_FAM%>% 
  group_by(as_factor(NCHLT5)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(NCHLT5, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 9. AGE_HEAD, AGE_MOM, AGE_POP, AGE_SP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
AGE<-df%>%
  select(AGE_HEAD, AGE_MOM, AGE_POP, AGE_SP)
```

### 9.1 AGE_HEAD (summary)

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
summary(df$AGE_HEAD)
```

### 9.2 AGE_MOM (summary)

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
summary(df$AGE_MOM)
```

### 9.3 AGE_POP (summary)

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
summary(df$AGE_POP)
```

### 9.4 AGE_SP (summary)

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
summary(df$AGE_SP)
```

### 10. ELDCH and YNGCH

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
ELDCH0<-df%>%
  select(ELDCH, YNGCH)
```

### 10.1 Frequencies in ELDCH

`r attributes(df$ELDCH)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
ELDCH<- ELDCH0%>% 
  group_by(as_factor(ELDCH)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

colnames(ELDCH)<-c("ELDCH","n","nrel")

a_0_4<-c("0","1","2","3","4")
a_5_9<-c("5","6","7","8","9")
a_10_14<-c("10","11","12","13","14")
a_15_19<-c("15","16","17","18","19")
a_20_24<-c("20","21","22","23","24")
a_25_29<-c("25","26","27","28","29")
a_30_34<-c("30","31","32","33","34")
a_35_39<-c("35","36","37","38","39")
a_40_44<-c("40","41","42","43","44")
a_40_44<-c("40","41","42","43","44")
a_45_49<-c("45","46","47","48","49")


ELDCH$ELDCH<-as.character(ELDCH$ELDCH)
ELDCH$AGE2<-with(ELDCH,ifelse(ELDCH%in%a_0_4, "0-4",
                       ifelse(ELDCH%in%a_5_9, "5-9",
                       ifelse(ELDCH%in%a_10_14, "10-14",
                       ifelse(ELDCH%in%a_15_19, "15-19",
                       ifelse(ELDCH%in%a_20_24, "20-24",
                       ifelse(ELDCH%in%a_25_29, "25-29",
                       ifelse(ELDCH%in%a_30_34, "30-34",
                       ifelse(ELDCH%in%a_35_39, "35-39",
                       ifelse(ELDCH%in%a_40_44, "40-44",
                       ifelse(ELDCH%in%a_45_49, "45-49",ELDCH)))))))))))

ELDCH$AGE2<-as.factor(ELDCH$AGE2)


ELDCH$AGE2<-factor(ELDCH$AGE2, levels=c("0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50 or older","No own child in household"))

ELDCH_AGE2<- ELDCH%>% 
  group_by(AGE2) %>% 
  summarise(n=sum(n))%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(ELDCH_AGE2, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%column_spec(1, width = "30em")
```

### 10.2 Frequencies in YNGCH

`r attributes(df$YNGCH)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
YNGCH<- ELDCH0%>% 
  group_by(as_factor(YNGCH)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

colnames(YNGCH)<-c("YNGCH","n","nrel")

a_0_4<-c("0","1","2","3","4")
a_5_9<-c("5","6","7","8","9")
a_10_14<-c("10","11","12","13","14")
a_15_19<-c("15","16","17","18","19")
a_20_24<-c("20","21","22","23","24")
a_25_29<-c("25","26","27","28","29")
a_30_34<-c("30","31","32","33","34")
a_35_39<-c("35","36","37","38","39")
a_40_44<-c("40","41","42","43","44")
a_40_44<-c("40","41","42","43","44")
a_45_49<-c("45","46","47","48","49")


YNGCH$YNGCH<-as.character(YNGCH$YNGCH)
YNGCH$AGE2<-with(YNGCH,ifelse(YNGCH%in%a_0_4, "0-4",
                       ifelse(YNGCH%in%a_5_9, "5-9",
                       ifelse(YNGCH%in%a_10_14, "10-14",
                       ifelse(YNGCH%in%a_15_19, "15-19",
                       ifelse(YNGCH%in%a_20_24, "20-24",
                       ifelse(YNGCH%in%a_25_29, "25-29",
                       ifelse(YNGCH%in%a_30_34, "30-34",
                       ifelse(YNGCH%in%a_35_39, "35-39",
                       ifelse(YNGCH%in%a_40_44, "40-44",
                       ifelse(YNGCH%in%a_45_49, "45-49",YNGCH)))))))))))

YNGCH$AGE2<-as.factor(YNGCH$AGE2)


YNGCH$AGE2<-factor(YNGCH$AGE2, levels=c("0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50 or older","No own child in household"))

YNGCH_AGE2<- YNGCH%>% 
  group_by(AGE2) %>% 
  summarise(n=sum(n))%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(YNGCH_AGE2, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>% column_spec(1, width = "30em")
```

### 11. NUMBER OF CHILDREN BORN: CHBORN, CHSURV

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CHBORN_SURV<-df%>%
  select(CHBORN,CHSURV)
```

### 11.1 Frequencies CHBORN

`r attributes(df$CHBORN)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CHBORN<- CHBORN_SURV%>% 
  group_by(as_factor(CHBORN)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(CHBORN, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 11.2 Frequencies CHSURV

`r attributes(df$CHSURV)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CHSURV<- CHBORN_SURV%>% 
  group_by(as_factor(CHSURV)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(CHSURV, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 12. FAMSIZE

`r attributes(df$FAMSIZE)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
FAMSIZE0<-df%>%
  select(FAMSIZE)
```

### 12.1 Frequencies in FAMSIZE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
FAMSIZE<- FAMSIZE0%>% 
  group_by(as_factor(FAMSIZE)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(FAMSIZE, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13. EDUCATION: EDATTAIN, EDATTAIND

`r attributes(df$EDATTAIN_HEAD)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN<-df%>%
  select(EDATTAIN,EDATTAIND)
```

### 13.1 Frequencies EDATTAIN

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN0<- EDATTAIN%>% 
  group_by(as_factor(EDATTAIN)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIN0, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13.2 Frequencies EDATTAIND

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIND<- EDATTAIN%>% 
  group_by(as_factor(EDATTAIND)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIND, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13.3 EDATTAIN_HEAD, EDATTAIN_MOM, EDATTAIN_POP, EDATTAIN_SP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN1<-df%>%
  select(EDATTAIN_HEAD, EDATTAIN_MOM, EDATTAIN_POP, EDATTAIN_SP)
```

### 13.4 Frequencies EDATTAIN_HEAD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN_HEAD<- EDATTAIN1%>% 
  group_by(as_factor(EDATTAIN_HEAD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIN_HEAD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13.5 Frequencies EDATTAIN_MOM

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN_MOM<- EDATTAIN1%>% 
  group_by(as_factor(EDATTAIN_MOM)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIN_MOM, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 13.6 Frequencies EDATTAIN_POP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN_POP<- EDATTAIN1%>% 
  group_by(as_factor(EDATTAIN_POP)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIN_POP, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 13.7 Frequencies EDATTAIN_SP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EDATTAIN_SP<- EDATTAIN1%>% 
  group_by(as_factor(EDATTAIN_SP)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EDATTAIN_SP, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13.8 SCHOOL

`r attributes(df$SCHOOL)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
SCHOOL0<-df%>%
  select(SCHOOL)
```

### 13.9 Frequencies in SCHOOL

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
SCHOOL<- SCHOOL0%>% 
  group_by(as_factor(SCHOOL)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(SCHOOL, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 13.10 LIT

`r attributes(df$LIT)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
LIT0<-df%>%
  select(LIT)
```

### 13.11 Frequencies in LIT

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
LIT<- LIT0%>% 
  group_by(as_factor(LIT)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(LIT, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 14. LABOUR FORCE: EMPSTAT, EMPSTATD

`r attributes(df$EMPSTAT)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT<-df%>%
  select(EMPSTAT, EMPSTATD)
```

### 14.1 Frequencies EMPSTAT

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT0<- EMPSTAT%>% 
  group_by(as_factor(EMPSTAT)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT0, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.2 Frequencies EMPSTATD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTATD<- EMPSTAT%>% 
  group_by(as_factor(EMPSTATD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT0, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.3 EMPSTAT_HEAD, EMPSTAT_MOM, EMPSTAT_POP, EMPSTT_SP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT1<-df%>%
  select(EMPSTAT_HEAD, EMPSTAT_MOM, EMPSTAT_POP, EMPSTAT_SP)
```

### 14.4 Frequencies EMPSTAT_HEAD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT_HEAD<- EMPSTAT1%>% 
  group_by(as_factor(EMPSTAT_HEAD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT_HEAD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.5 Frequencies EMPSTAT_MOM

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT_MOM<- EMPSTAT1%>% 
  group_by(as_factor(EMPSTAT_MOM)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT_MOM, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.6 Frequencies EMPSTAT_POP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT_POP<- EMPSTAT1%>% 
  group_by(as_factor(EMPSTAT_POP)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT_POP, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.7 Frequencies EMPSTAT_SP

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
EMPSTAT_SP<- EMPSTAT1%>% 
  group_by(as_factor(EMPSTAT_SP)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(EMPSTAT_SP, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 14.8 LABFORCE

`r attributes(df$LABFORCE)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
LABFORCE0<-df%>%
  select(LABFORCE)
```

### 14.9 Frequencies in LABFORCE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
LABFORCE<- LABFORCE0%>% 
  group_by(as_factor(LABFORCE)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(LABFORCE, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 14.10 OCCISCO

`r attributes(df$OCCISCO)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
OCCISCO0<-df%>%
  select(OCCISCO)
```

### 14.11 Frequencies in OCCISCO

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
OCCISCO<- OCCISCO0%>% 
  group_by(as_factor(OCCISCO)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(OCCISCO, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 14.12 STATUS OF ECONOMICALLY ACTIVE PERSON: CLASSWK, CLASSWKD

`r attributes(df$CLASSWK)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CLASSWK0<-df%>%
  select(CLASSWK, CLASSWKD)
```

### 14.13 Frequencies in CLASSWK

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CLASSWK<- CLASSWK0%>% 
  group_by(as_factor(CLASSWK)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(CLASSWK, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 14.14 Frequencies in CLASSWKD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CLASSWKD<- CLASSWK0%>% 
  group_by(as_factor(CLASSWKD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(CLASSWKD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 14.15 INDGEN

`r attributes(df$INDGEN)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
INDGEN0<-df%>%
  select(INDGEN)
```

### 14.16 Frequencies in INDGEN

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
INDGEN<- INDGEN0%>% 
  group_by(as_factor(INDGEN)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(INDGEN, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")
```

### 15. OWNERSHIP, OWNERSHIPD, HHTYPE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
OWNHHT<-df%>%
  select(OWNERSHIP, OWNERSHIPD, HHTYPE)
```

### 15.1 Frequencies OWNERSHIP

`r attributes(df$OWNERSHIP)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
OWNERSHIP<- OWNHHT%>% 
  group_by(as_factor(OWNERSHIP)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(OWNERSHIP, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 15.2 Frequencies OWNERSHIPD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
OWNERSHIPD<- OWNHHT%>% 
  group_by(as_factor(OWNERSHIPD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(OWNERSHIPD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 15.3 Frequencies HHTYPE

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
HHTYPE<- OWNHHT%>% 
  group_by(as_factor(HHTYPE)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(HHTYPE, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 16. MARITAL STATUS: MARST, MARSTD, CONSENS

`r attributes(df$MARST)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
MARS<-df%>%
  select(MARST, MARSTD, CONSENS)
```

### 16.1 Frequencies MARST

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
MARST<- MARS%>% 
  group_by(as_factor(MARST)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(MARST, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 16.2 Frequencies MARSTD

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
MARSTD<- MARS%>% 
  group_by(as_factor(MARSTD)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(MARSTD, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 16.3 Frequencies CONSENS

`r attributes(df$CONSENS)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
CONSENS<- MARS%>% 
  group_by(as_factor(CONSENS)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(CONSENS, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 17. REGIONW, GEOLEV1, GEOLEV2

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
GEO<-df%>%
  select(REGIONW, GEOLEV1, GEOLEV2)
```

### 17.1 Frequencies REGIONW

`r attributes(df$REGIONW)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
REGIONW<- GEO%>%
  group_by(as_factor(REGIONW)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(REGIONW, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 17.2 Frequencies GEOLEV1

`r attributes(df$GEOLEV1)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
GEOLEV1<- GEO%>%
  group_by(as_factor(GEOLEV1)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(GEOLEV1, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 17.3 Number of unique codes in GEOLEV2

**Number of unique codes:** `r length(unique(df$GEOLEV2))`.

### 18. PERNUM, PERWT

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
PER<-df%>%
  select(PERNUM, PERWT)
```

### 18.1 Frequencies PERNUM

`r attributes(df$PERNUM)$var_desc`

```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE
PERNUM<- PER%>%
  group_by(as_factor(PERNUM)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))

kbl(PERNUM, "latex", longtable = T, booktabs = T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

### 18.2 Frequencies PERWT

`r attributes(df$PERWT)$var_desc`


```{r fig.width=12, fig.height=6}
#| echo: false
#| warning: FALSE

#There is a problem of codification with in this variable. The next table just shows the first ten cases as an example. 
PERWT<- PER%>%
  group_by(as_factor(PERWT)) %>% 
  summarise(n=n())%>% 
  mutate(n_rel = round(n / sum(n)*100,2))#%>% 
  #head(10)

kbl(PERWT, booktabs = T, "latex", longtable=T)%>%kable_styling(position = "center") %>%
column_spec(1, width = "30em")

```

------------------------------------------------------------------------


